# Generated by Django 3.0.8 on 2020-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20200907_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='InitialSetupCharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='IsProduct',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
