# Generated by Django 3.0.8 on 2020-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200916_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounttype',
            old_name='Discount',
            new_name='DiscountCode',
        ),
        migrations.RemoveField(
            model_name='discounttype',
            name='DiscountNameUnchanged',
        ),
        migrations.AddField(
            model_name='discounttype',
            name='DiscountDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
