# Generated by Django 3.0.8 on 2020-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20200916_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Is_ForMe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Is_ForMeAndFamily',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
