# Generated by Django 3.0.8 on 2020-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200917_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NoOfInstallmentMonths',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
