# Generated by Django 3.0.8 on 2020-09-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20200923_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='SameHousehold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='within_same_family', to='adminpanel.Customer'),
        ),
    ]
