# Generated by Django 3.0.8 on 2020-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20200928_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='IsDiscountable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='discounttype',
            name='Percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
