# Generated by Django 3.0.8 on 2020-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_product_discountpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='Percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='DiscountPercentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
