# Generated by Django 3.0.8 on 2020-10-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_auto_20201001_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ReferralDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.DiscountType'),
        ),
    ]
