# Generated by Django 3.0.8 on 2020-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_customer_referraldiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='PersonalDiscount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
