# Generated by Django 3.0.8 on 2020-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20201002_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='AdditionalMemberPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
