# Generated by Django 3.0.8 on 2020-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_product_additionalmemberprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Is_ForMe',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Is_ForMeAndFamily',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='TotalNoOfPerson',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
