# Generated by Django 3.0.8 on 2020-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_auto_20201015_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DetailDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
