# Generated by Django 3.0.8 on 2020-10-22 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_auto_20201020_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentdue',
            name='Installment_Type_Id',
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='Amount_Due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Customer'),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='InstalmentDueDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='InstalmentReminderDay',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='PaymentRefId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Payment'),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Order')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscountEligibility',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DiscountApplicableLimit', models.IntegerField(blank=True, default=1, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Customer')),
                ('DiscountType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.DiscountType')),
            ],
        ),
    ]
