# Generated by Django 3.0.8 on 2020-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_auto_20201023_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPost',
            fields=[
                ('Announcement_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title1', models.CharField(blank=True, max_length=2000, null=True)),
                ('Title2', models.CharField(blank=True, max_length=2000, null=True)),
                ('Description', models.CharField(blank=True, max_length=2000, null=True)),
                ('PostImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
