# Generated by Django 3.0.8 on 2020-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_announcementpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentdue',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='installmentdue',
            name='User',
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='Customer_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentdue',
            name='User_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='OrderCompletionDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
