# Generated by Django 3.0.8 on 2020-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_auto_20201029_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdue',
            name='PaymentRefId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
