# Generated by Django 3.0.8 on 2020-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_order_actualamounttopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='FullPaymentDiscountAmount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
