# Generated by Django 3.0.8 on 2020-10-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_auto_20201029_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdiscounteligibility',
            old_name='DiscountType',
            new_name='DiscountType_Id',
        ),
    ]
