# Generated by Django 3.0.8 on 2020-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_auto_20201029_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='DisplayName',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
