# Generated by Django 3.0.8 on 2020-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_configuration_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
