# Generated by Django 3.0.8 on 2020-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_auto_20201120_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='StockLevel',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Threshold',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
