# Generated by Django 3.0.8 on 2020-12-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_auto_20201120_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='IsSubscriptionCanceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Stripe_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Stripe_Subscription_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('ProductSpec_Id', models.AutoField(primary_key=True, serialize=False)),
                ('SpecificationName', models.CharField(blank=True, max_length=2000, null=True)),
                ('SpecificationValue', models.CharField(blank=True, max_length=2000, null=True)),
                ('Product', models.ForeignKey(blank=True, db_column='Product_Id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Product')),
            ],
        ),
    ]
