# Generated by Django 3.0.8 on 2020-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_auto_20201202_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentdue',
            name='IsInstalmentPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
