# Generated by Django 3.0.8 on 2020-12-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_payment_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='OrderDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.OrderDetails'),
        ),
    ]
