# Generated by Django 3.0.8 on 2021-01-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_auto_20201210_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='IsSubscriptionCanceled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Stripe_Subscription_Id',
        ),
    ]
