# Generated by Django 3.0.8 on 2021-02-01 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_auto_20210107_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='CreatedDate',
            new_name='LogCreatedDate',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='CreatedBy',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
