# Generated by Django 3.0.8 on 2021-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_auto_20210201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ActivityDescription',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
    ]
