# Generated by Django 3.0.8 on 2021-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_auto_20210201_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ActivityDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
