# Generated by Django 3.0.8 on 2021-02-01 20:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_auto_20210201_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ActivityDescription',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
