# Generated by Django 3.0.8 on 2021-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_auto_20210201_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
