# Generated by Django 3.0.8 on 2021-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0050_address_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderNotes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
