# Generated by Django 2.2.14 on 2020-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManorPharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
